#!/usr/bin/env python3
"""Generate shared TypeScript and Python protocol contracts from JSON Schema."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

CONTRACTS_ROOT = Path(__file__).resolve().parents[1]
SCHEMAS_ROOT = CONTRACTS_ROOT / "schemas" / "v1"
GENERATED_TS_PATH = CONTRACTS_ROOT / "generated" / "typescript" / "protocol-contracts.d.ts"
GENERATED_PY_PACKAGE = CONTRACTS_ROOT / "generated" / "python" / "openvman_contracts"
GENERATED_PY_PATH = GENERATED_PY_PACKAGE / "protocol_contracts.py"
GENERATED_PY_INIT_PATH = GENERATED_PY_PACKAGE / "__init__.py"
GENERATED_PY_TYPED_PATH = GENERATED_PY_PACKAGE / "py.typed"


@dataclass(slots=True)
class NestedType:
    name: str
    schema: dict[str, Any]


@dataclass(slots=True)
class EventDefinition:
    event_name: str
    schema: dict[str, Any]
    direction: str
    class_name: str
    nested_types: list[NestedType] = field(default_factory=list)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated files are out of date.")
    args = parser.parse_args()

    manifest = _read_json(SCHEMAS_ROOT / "manifest.json")
    event_definitions = _load_event_definitions(manifest)
    generated_files = {
        GENERATED_TS_PATH: render_typescript_contracts(manifest, event_definitions),
        GENERATED_PY_PATH: render_python_contracts(manifest, event_definitions),
        GENERATED_PY_INIT_PATH: render_python_init(),
        GENERATED_PY_TYPED_PATH: "",
    }

    if args.check:
        stale_files = [
            path
            for path, content in generated_files.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale_files:
            print("Generated protocol contracts are out of date:", file=sys.stderr)
            for path in stale_files:
                print(f"- {path.relative_to(CONTRACTS_ROOT.parent)}", file=sys.stderr)
            return 1
        return 0

    for path, content in generated_files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    print("Generated protocol contracts:")
    for path in generated_files:
        print(f"- {path.relative_to(CONTRACTS_ROOT.parent)}")
    return 0


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def _load_event_definitions(manifest: dict[str, Any]) -> list[EventDefinition]:
    return [
        _build_event_definition(event_name, event_config)
        for event_name, event_config in manifest["events"].items()
    ]


def _build_event_definition(event_name: str, event_config: dict[str, Any]) -> EventDefinition:
    schema = _read_json(SCHEMAS_ROOT / event_config["schema"])
    return EventDefinition(
        event_name=event_name,
        schema=schema,
        direction=event_config["direction"],
        class_name=f"{_pascal_case(event_name)}Event",
        nested_types=_collect_nested_types(event_name, schema),
    )


def _collect_nested_types(event_name: str, schema: dict[str, Any]) -> list[NestedType]:
    nested_types: list[NestedType] = []
    for property_name, property_schema in schema.get("properties", {}).items():
        item_schema = _array_object_item_schema(property_schema)
        if item_schema is None:
            continue
        nested_types.append(
            NestedType(
                name=_nested_type_name(event_name, property_name),
                schema=item_schema,
            )
        )
    return nested_types


def render_typescript_contracts(
    manifest: dict[str, Any],
    event_definitions: list[EventDefinition],
) -> str:
    client_definitions = _definitions_for_direction(event_definitions, "client_to_server")
    server_definitions = _definitions_for_direction(event_definitions, "server_to_client")

    lines = [
        "// Generated by contracts/scripts/generate_protocol_contracts.py. Do not edit manually.",
        "",
        f'export const PROTOCOL_NAME = "{manifest["protocol"]}";',
        f'export const DEFAULT_PROTOCOL_VERSION = "{manifest["version"]}";',
        "",
        'export type ProtocolDirection = "client_to_server" | "server_to_client";',
        f"export type ProtocolEventName = {_render_ts_string_union(_event_names(event_definitions))};",
        f"export type ClientEventName = {_render_ts_string_union(_event_names(client_definitions))};",
        f"export type ServerEventName = {_render_ts_string_union(_event_names(server_definitions))};",
        "",
        "export interface ContractEventEntry {",
        "  direction: ProtocolDirection;",
        "  schema: string;",
        "}",
        "",
        "export interface ContractManifest {",
        "  protocol: string;",
        "  version: string;",
        "  schema_dialect: string;",
        "  events: Record<ProtocolEventName, ContractEventEntry>;",
        "}",
        "",
    ]

    for definition in event_definitions:
        for nested_type in definition.nested_types:
            lines.extend(_render_ts_interface(nested_type.name, nested_type.schema))
            lines.append("")

    for definition in event_definitions:
        lines.extend(_render_ts_interface(definition.class_name, definition.schema))
        lines.append("")

    lines.extend(
        [
            f"export type ClientEvent = {' | '.join(_class_names(client_definitions))};",
            f"export type ServerEvent = {' | '.join(_class_names(server_definitions))};",
            "export type ProtocolEvent = ClientEvent | ServerEvent;",
            "",
        ]
    )
    return "\n".join(lines).strip() + "\n"


def _render_ts_interface(name: str, schema: dict[str, Any]) -> list[str]:
    required_fields = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for property_name, property_schema in schema.get("properties", {}).items():
        optional = "" if property_name in required_fields else "?"
        lines.append(
            f"  {property_name}{optional}: {_render_ts_type(property_name, property_schema, name)};"
        )
    lines.append("}")
    return lines


def _render_ts_type(property_name: str, schema: dict[str, Any], parent_name: str) -> str:
    if "const" in schema:
        return _ts_string_literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_ts_string_literal(value) for value in schema["enum"])

    schema_type = schema.get("type")
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "object":
        if schema.get("additionalProperties", {}).get("type") == "string":
            return "Record<string, string>"
        return "Record<string, unknown>"
    if schema_type == "array":
        item_schema = schema["items"]
        if item_schema.get("type") == "object":
            return f"{_nested_type_name(_event_name_from_class_name(parent_name), property_name)}[]"
        return f"{_render_ts_type(property_name, item_schema, parent_name)}[]"
    raise ValueError(f"Unsupported TypeScript schema fragment: {schema}")


def render_python_contracts(
    manifest: dict[str, Any],
    event_definitions: list[EventDefinition],
) -> str:
    client_definitions = _definitions_for_direction(event_definitions, "client_to_server")
    server_definitions = _definitions_for_direction(event_definitions, "server_to_client")

    lines = [
        '"""Generated by contracts/scripts/generate_protocol_contracts.py. Do not edit manually."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Annotated, Literal, TypeAlias",
        "",
        "from pydantic import BaseModel, ConfigDict, Field, TypeAdapter",
        "",
        f'PROTOCOL_NAME = "{manifest["protocol"]}"',
        f'DEFAULT_PROTOCOL_VERSION = "{manifest["version"]}"',
        'ProtocolDirection: TypeAlias = Literal["client_to_server", "server_to_client"]',
        "",
        "",
        "class GeneratedProtocolModel(BaseModel):",
        '    model_config = ConfigDict(extra="forbid")',
        "",
    ]

    for definition in event_definitions:
        for nested_type in definition.nested_types:
            lines.extend(_render_python_model(nested_type.name, nested_type.schema))
            lines.append("")

    for definition in event_definitions:
        lines.extend(_render_python_model(definition.class_name, definition.schema))
        lines.append("")

    lines.extend(
        [
            f"ClientEvent = Annotated[{ ' | '.join(_class_names(client_definitions)) }, Field(discriminator='event')]",
            f"ServerEvent = Annotated[{ ' | '.join(_class_names(server_definitions)) }, Field(discriminator='event')]",
            "ProtocolEvent = ClientEvent | ServerEvent",
            "",
            "CLIENT_EVENT_ADAPTER = TypeAdapter(ClientEvent)",
            "SERVER_EVENT_ADAPTER = TypeAdapter(ServerEvent)",
            "",
            "__all__ = [",
            '    "CLIENT_EVENT_ADAPTER",',
            '    "ClientEvent",',
        ]
    )
    exported_names = [
        "DEFAULT_PROTOCOL_VERSION",
        "GeneratedProtocolModel",
        "PROTOCOL_NAME",
        "ProtocolDirection",
        "ProtocolEvent",
        "SERVER_EVENT_ADAPTER",
        "ServerEvent",
    ]
    for definition in event_definitions:
        exported_names.append(definition.class_name)
        exported_names.extend(nested_type.name for nested_type in definition.nested_types)
    for name in sorted(set(exported_names)):
        lines.append(f'    "{name}",')
    lines.append("]")
    return "\n".join(lines).strip() + "\n"


def _render_python_model(name: str, schema: dict[str, Any]) -> list[str]:
    required_fields = set(schema.get("required", []))
    lines = [f"class {name}(GeneratedProtocolModel):"]
    for property_name, property_schema in schema.get("properties", {}).items():
        lines.append(
            _render_python_field(name, property_name, property_schema, property_name in required_fields)
        )
    if len(lines) == 1:
        lines.append("    pass")
    return lines


def _render_python_field(
    model_name: str,
    property_name: str,
    schema: dict[str, Any],
    required: bool,
) -> str:
    type_expr = _render_python_type(model_name, property_name, schema)
    field_args = _build_python_field_args(schema, required)

    if required and not field_args:
        return f"    {property_name}: {type_expr}"

    if required:
        return f"    {property_name}: {type_expr} = Field({', '.join(field_args)})"

    if schema.get("default") == {}:
        return f"    {property_name}: {type_expr} = Field(default_factory=dict)"

    optional_type = f"{type_expr} | None"
    field_args = ["default=None", *field_args]
    return f"    {property_name}: {optional_type} = Field({', '.join(field_args)})"


def _render_python_type(model_name: str, property_name: str, schema: dict[str, Any]) -> str:
    if "const" in schema:
        return f"Literal[{_python_literal(schema['const'])}]"
    if "enum" in schema:
        return f"Literal[{', '.join(_python_literal(value) for value in schema['enum'])}]"

    schema_type = schema.get("type")
    if schema_type == "string":
        return "str"
    if schema_type == "integer":
        return "int"
    if schema_type == "number":
        return "float"
    if schema_type == "boolean":
        return "bool"
    if schema_type == "object":
        if schema.get("additionalProperties", {}).get("type") == "string":
            return "dict[str, str]"
        return "dict[str, object]"
    if schema_type == "array":
        item_schema = schema["items"]
        if item_schema.get("type") == "object":
            return f"list[{_nested_type_name(_event_name_from_class_name(model_name), property_name)}]"
        return f"list[{_render_python_type(model_name, property_name, item_schema)}]"
    raise ValueError(f"Unsupported Python schema fragment: {schema}")


def _build_python_field_args(schema: dict[str, Any], required: bool) -> list[str]:
    field_args: list[str] = []
    schema_type = schema.get("type")
    if schema_type == "string":
        if "minLength" in schema:
            field_args.append(f"min_length={schema['minLength']}")
        if "maxLength" in schema:
            field_args.append(f"max_length={schema['maxLength']}")
        if "pattern" in schema:
            field_args.append(f"pattern={schema['pattern']!r}")
    if schema_type in {"integer", "number"} and "minimum" in schema:
        field_args.append(f"ge={schema['minimum']}")
    if required and not field_args and schema.get("default") == {}:
        field_args.append("default_factory=dict")
    return field_args


def render_python_init() -> str:
    return "\n".join(
        [
            '"""Generated shared protocol contracts."""',
            "",
            "from .protocol_contracts import *",
            "",
        ]
    )


def _pascal_case(value: str) -> str:
    return "".join(part.capitalize() for part in value.replace("-", "_").split("_") if part)


def _array_object_item_schema(schema: dict[str, Any]) -> dict[str, Any] | None:
    if schema.get("type") != "array":
        return None
    item_schema = schema.get("items", {})
    if item_schema.get("type") != "object":
        return None
    return item_schema


def _definitions_for_direction(
    event_definitions: list[EventDefinition],
    direction: str,
) -> list[EventDefinition]:
    return [definition for definition in event_definitions if definition.direction == direction]


def _event_names(event_definitions: list[EventDefinition]) -> list[str]:
    return [definition.event_name for definition in event_definitions]


def _class_names(event_definitions: list[EventDefinition]) -> list[str]:
    return [definition.class_name for definition in event_definitions]


def _singularize(value: str) -> str:
    return value[:-1] if value.endswith("s") else value


def _nested_type_name(event_name: str, property_name: str) -> str:
    if event_name == "server_stream_chunk" and property_name == "visemes":
        return "VisemeFrame"
    return f"{_pascal_case(event_name)}{_pascal_case(_singularize(property_name))}"


def _event_name_from_class_name(class_name: str) -> str:
    name = class_name[:-5] if class_name.endswith("Event") else class_name
    chunks: list[str] = []
    current = ""
    for char in name:
        if char.isupper() and current:
            chunks.append(current.lower())
            current = char
        else:
            current += char
    if current:
        chunks.append(current.lower())
    return "_".join(chunks)


def _python_literal(value: str) -> str:
    return repr(value)


def _render_ts_string_union(values: list[str]) -> str:
    return " | ".join(_ts_string_literal(value) for value in values)


def _ts_string_literal(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


if __name__ == "__main__":
    raise SystemExit(main())
